import { GameConfig } from '../engine/types';

export interface ExtendedGameConfig extends GameConfig {
  icon: string;
  rules: string[];
  playModes: ('ai' | 'online' | 'private' | 'solo')[];
  category: 'card' | 'board' | 'strategy';
}

export const GAME_CONFIGS: Record<string, ExtendedGameConfig> = {
  chess: {
    id: 'chess',
    name: 'Chess',
    description: 'The king of strategy games. Play against AI at any difficulty.',
    minPlayers: 2,
    maxPlayers: 2,
    hasAI: true,
    thumbnail: '',
    color: '#5a3219',
    icon: '\u265A',
    category: 'board',
    playModes: ['ai', 'online', 'private'],
    rules: [
      'Each piece moves differently: pawns forward, rooks in lines, bishops diagonally, etc.',
      'Capture opponent pieces by moving to their square',
      'Put the enemy King in checkmate (no escape from attack) to win',
      'Special moves: castling, en passant, and pawn promotion',
    ],
  },
  solitaire: {
    id: 'solitaire',
    name: 'Solitaire',
    description: 'Classic Klondike solitaire. Sort all cards into foundation piles by suit.',
    minPlayers: 1,
    maxPlayers: 1,
    hasAI: false,
    thumbnail: '',
    color: '#166534',
    icon: '\u2660',
    category: 'card',
    playModes: ['solo'],
    rules: [
      'Move cards between 7 tableau columns, building down in alternating colors',
      'Turn cards from the stock pile to find playable cards',
      'Build foundation piles from Ace to King by suit',
      'Win by moving all 52 cards to the 4 foundation piles',
    ],
  },
  hearts: {
    id: 'hearts',
    name: 'Hearts',
    description: 'Classic trick-taking card game. Avoid hearts and the Queen of Spades.',
    minPlayers: 4,
    maxPlayers: 4,
    hasAI: true,
    thumbnail: '',
    color: '#991b1b',
    icon: '\u2665',
    category: 'card',
    playModes: ['ai', 'online', 'private'],
    rules: [
      'Pass 3 cards to another player each round, then play tricks',
      'Follow the lead suit if possible; highest card of lead suit wins the trick',
      'Each Heart = 1 point, Queen of Spades = 13 points (points are bad!)',
      'Or "Shoot the Moon" by taking ALL hearts + Queen of Spades to give 26 points to everyone else',
    ],
  },
  checkers: {
    id: 'checkers',
    name: 'Checkers',
    description: 'Jump and capture your way to victory on the classic 8x8 board.',
    minPlayers: 2,
    maxPlayers: 2,
    hasAI: true,
    thumbnail: '',
    color: '#713f12',
    icon: '\u26C0',
    category: 'board',
    playModes: ['ai', 'online', 'private'],
    rules: [
      'Move pieces diagonally forward on dark squares',
      'Jump over opponent pieces to capture them (mandatory if possible)',
      'Reach the opposite end to become a King - Kings move backwards too',
      'Win by capturing all opponent pieces or blocking all their moves',
    ],
  },
  rummy: {
    id: 'rummy',
    name: 'Gin Rummy',
    description: 'Form melds and go gin! Classic 2-player draw and discard card game.',
    minPlayers: 2,
    maxPlayers: 2,
    hasAI: true,
    thumbnail: '',
    color: '#1e3a5f',
    icon: '\u2666',
    category: 'card',
    playModes: ['ai', 'online', 'private'],
    rules: [
      'Draw a card from the stock or discard pile each turn, then discard one',
      'Form melds: sets of 3-4 same-rank cards, or runs of 3+ consecutive suited cards',
      'Knock when your deadwood (unmelded cards) totals 10 or less',
      'Go Gin with zero deadwood for bonus points! First to 100 wins',
    ],
  },
  battleship: {
    id: 'battleship',
    name: 'Sea Battle',
    description: 'Place your fleet and hunt the enemy. Classic or Advanced mode with special weapons.',
    minPlayers: 2,
    maxPlayers: 2,
    hasAI: true,
    thumbnail: '',
    color: '#0f4c5c',
    icon: '\u2693',
    category: 'strategy',
    playModes: ['ai', 'online', 'private'],
    rules: [
      'Classic: 5 ships on a 10×10 grid. Advanced: 6 ships on a 12×12 grid with special weapons',
      'Drag and drop ships onto your grid during placement (R to rotate)',
      'Take turns firing shots at the enemy grid to find their ships',
      'Advanced weapons: Torpedoes (cross), Depth Charges (3×3), Airstrikes (row of 5)',
      'Sink all enemy ships before they sink yours to win!',
    ],
  },
  backgammon: {
    id: 'backgammon',
    name: 'Backgammon',
    description: 'Roll the dice and race your checkers home. The oldest board game in the world.',
    minPlayers: 2,
    maxPlayers: 2,
    hasAI: true,
    thumbnail: '',
    color: '#5c3a1a',
    icon: '\u{1F3B2}',
    category: 'board',
    playModes: ['ai'],
    rules: [
      'Roll two dice and move your 15 checkers toward your home board',
      'Land on a point with a single opponent checker to send it to the bar',
      'Checkers on the bar must re-enter before you can move other pieces',
      'Once all your checkers are in your home board, bear them off to win',
      'Doubles let you move four times instead of two!',
    ],
  },
  bonks: {
    id: 'bonks',
    name: 'BooBonks, BoJangles & Chonk',
    description: 'Pick your hero and save Fizzlewood! A pixel-art platformer adventure.',
    minPlayers: 1,
    maxPlayers: 1,
    hasAI: false,
    thumbnail: '',
    color: '#cc3399',
    icon: '\u{1F3AE}',
    category: 'strategy',
    playModes: ['solo'],
    rules: [
      'Choose BooBonks, BoJangles, or Chonk the dog - each with unique abilities',
      'Run, jump, and stomp through 8 levels across 4 worlds to save Fizzlewood',
      'Collect Sparkstones, defeat King Grumble\'s minions, and grab power-ups',
      'Hit ? blocks for mushrooms, fire flowers, stars, and dog treats',
      'Reach the flag at the end of each level to advance',
    ],
  },
  quest3d: {
    id: 'quest3d',
    name: 'Sparkstone Quest',
    description: 'Explore a PS1-style low-poly town. A 3D tech demo powered by Three.js.',
    minPlayers: 1,
    maxPlayers: 1,
    hasAI: false,
    thumbnail: '',
    color: '#4a6741',
    icon: '\u{1F3F0}',
    category: 'strategy',
    playModes: ['solo'],
    rules: [
      'Explore a procedurally-built low-poly town inspired by PS1-era RPGs',
      'Drag the mouse to orbit the camera around the town',
      'Scroll to zoom in and out, WASD keys to pan around',
      'A tech demo showcasing real-time 3D rendering with Three.js',
    ],
  },
};

export function getGameConfig(gameId: string): ExtendedGameConfig | undefined {
  return GAME_CONFIGS[gameId];
}

export function getAllGames(): ExtendedGameConfig[] {
  return Object.values(GAME_CONFIGS);
}
